### ISSUE TITLE
createPs function stopped with ILLCONDITIONED Calls

### ISSUE THREAD

**Issue by BlingArida** [OHDSI/CohortMethod#121]
Dear developers,

I am running a PLE package and encounter the issue:
createPs(stopOnError = TRUE, excludeCovariateIds = list(), prior = list( :    ILLCONDITIONED Calls

I put error message bellow, could you help point out which part of setting should I look into?

```
Message:  ILLCONDITIONED
Level:  FATAL
Time:  2022-06-07 13:31:31

Stack trace:
6: ParallelLogger::logFatal(conditionMessage(e))
5: h(simpleError(msg, call))
4: .handleSimpleError(function (e) 
{
    ParallelLogger::logFatal(conditionMe
3: stop(cyclopsFit$return_flag)
2: createPs(stopOnError = TRUE, excludeCovariateIds = list(), prior = list(1, 
1: do.call("createPs", args)


Thread: Main
Message:  Error in ParallelLogger::clusterApply(cluster, modelsToFit, fitSharedPsModel,  :    Error(s) when calling function 'fun', see earlier messages for details Calls: sourceWithProgress ... execute -> runCohortMethod -> <Anonymous> -> <Anonymous> 
Level:  FATAL
Time:  2022-06-07 13:31:45

Stack trace:
10: logFatal(gsub("\n", " ", geterrmessage()))
9: (function () 
{
    logFatal(gsub("\n", " ", geterrmessage()))
    if (!is.
8: stop(message)
7: ParallelLogger::clusterApply(cluster, modelsToFit, fitSharedPsModel, refitP
6: CohortMethod.R#60: CohortMethod::runCmAnalyses(connectionDetails = connecti
5: Main.R#123: runCohortMethod(connectionDetails = connectionDetails, cdmDatab
4: execute(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatab
3: eval(statements[[idx]], envir = sourceEnv)
2: eval(statements[[idx]], envir = sourceEnv)
```

**Comment by schuemie** [comment]
The error message indicates there's something in the data that prevents the model from being fitted. Unfortunately, it is hard to say exactly what it is. It could for example be that there is nobody in the target group, or nobody in the comparator group. Or there could be no covariates that distinguish the two groups (Which would be odd, because we usually have many covariates). Or a collection of covariates together are perfectly predictive of treatment, even though no individual covariate is.

Some areas to explore:
- Check the attrition so far (e.g. by calling `getAttritionTable()` on the study population object
- Check if covariates are created (e.g. by calling `summary()` on the cohort method data object
- Make sure you excluded the exposure concepts from the covariates when calling `getDbCohortMethodData()`.  (see [here](https://ohdsi.github.io/CohortMethod/articles/SingleStudies.html#extracting-the-data-from-the-server))
