### ISSUE TITLE
Definition of time at risk

### ISSUE THREAD

**Issue by rekkasa** [OHDSI/CohortMethod#126]
I am trying to setup a study comparing treatment and control with regard to a certain outcome. I want to censor patients at a certain time point, e.g. 10 years. When I run the same analysis, once using the default settings (`riskWindowEnd = 0` and `endAnchor = "cohort end"`, i.e. look at the entire follow-up of the patient [?]) and the second time attempting to censor at 10 years after treatment initiation (`riskWindowEnd = 3650` and `endAnchor = "cohort start"`) I get very different HR estimates. From the KM plots I can see there is almost no patients after ~5 years. Looking at the population objects I get very different times at risk for the same patient under the two different settings.

In line [241](https://github.com/OHDSI/CohortMethod/blob/391b499c9e162f9cbc7c273baeb17c9eb2fdf4a4/R/StudyPopulation.R#L241), I understand that `riskEnd` is set equal to `daysToObsEnd` if the defined `riskWindowEnd` is larger than the `daysToObsEnd`. However, for an on-treatment analysis, I would expect that if a patient's time in the cohort was exceeded by the user-specified `riskWindowEnd`, then `riskEnd` should be set equal to `daysToCohortEnd` instead of `daysToObsEnd`. What am I missing here?

Some code to reproduce and maybe make what my question is clearer:

```r
library(CohortMethod)
library(dplyr)

set.seed(1234)
data(cohortMethodDataSimulationProfile)
sampleSize <- 1
tmpCmd <- simulateCohortMethodData(cohortMethodDataSimulationProfile, n = sampleSize)

cohortRow <- tmpCmd$cohorts %>%
  collect()

outcomeRow <- tmpCmd$outcomes %>%
  collect()

cohorts <- cohortRow
cohorts$rowId[1] <- 1
cohorts$daysToCohortEnd[1] <- 10
cohorts$daysToObsEnd[1] <- 20
tmpCmd$cohorts <- cohorts


createStudyPopulation(
  cohortMethodData = tmpCmd,
  outcomeId = 123,
  removeSubjectsWithPriorOutcome = FALSE,
  startAnchor = "cohort start",
  riskWindowStart = 0,
  endAnchor = "cohort start",
  riskWindowEnd = 9999,
  censorAtNewRiskWindow = T
) %>%
  pull(riskEnd)
```
I would have expected this number to be 10 instead of 20.

**Comment by schuemie** [comment]
The time at risk (TAR) is defined relative to your target and comparator cohorts, but is truncated by the observation period. 

CohortMethod doesn't know what your target and comparator cohorts are, it just knows the start and end dates. Suppose you want an on-treatment TAR, the first step is to make sure your cohort definition reflects the time on the treatment, so make sure cohort_start_date equals the day the treatment was initiated, and cohort_end_date equals the day the treatment was discontinued. The second step is to define the TAR relative to the cohort start and end date. A typical on-treatment TAR has 
```r
riskWindowStart = 0
startAnchor = "cohort start" 
riskWindowEnd = 0
endAnchor = "cohort end" 
```
meaning the TAR starts on the exact date of the cohort start date, and ends on the exact date of the cohort end date. 

A typical intent-to-treat (ITT) analysis (an analysis that follows subjects from initiation to as far as possible) has
```r
riskWindowStart = 0
startAnchor = "cohort start" 
riskWindowEnd = 99999
endAnchor = "cohort start" 
```
meaning the TAR starts on the exact date of the cohort start date, and ends somewhere really far in the future (relative to the cohort start date). 

In both cases, CohortMethod will then truncate the TAR at the end of the observation period. By definition, outside of the observation period we would not expect to observe outcomes even if they occurred, so we cannot use this time in our analysis. (This is what the `daysToObsEnd` variable is for).

Of course, the estimated HR can be very different between an on-treatment and ITT TAR. The ITT typically adds years of TAR not included in the on-treatment analysis. Typically, but not necessarily, the ITT estimate is much closer to the null.

**Your example**

In your example code, the answer is 20, because you defined an ITT window, and hard-coded the observation period end to occur 20 days after the index date. I'm unsure why you would think it would be 10, because your TAR doesn't anchor in the cohort end date.

**Comment by rekkasa** [comment]
That makes sense. I think I understand. So, in order to get the on-treatment population censored at, say, 365 days in the code above I would need to set

```r
createStudyPopulation(
  cohortMethodData = tmpCmd,
  outcomeId = 123,
  removeSubjectsWithPriorOutcome = FALSE,
  riskWindowStart = 0,
  startAnchor = "cohort start",
  riskWindowEnd = 0,
  endAnchor = "cohort end",
  censorAtNewRiskWindow = T,
  maxTimeAtRisk = 365
) 
```
Is that correct?

**Comment by schuemie** [comment]
That is correct! (Sorry for the long delay)

**Comment by rekkasa** [comment]
Thanks! You can go ahead and close the issue
