### ISSUE TITLE
Make sure we correctly handle all sources for exposures and outcomes

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortMethod#23]
The getDbCohortData correctly needs to handle fetching exposures from
1. drug_exposure
2. drug_era
3. cohort (either within the CDM schema or a separate schema)
and handle fetching outcomes from
1. condition_occurrence
2. condition_era
3. cohort (either within the CDM schema or a separate schema)
In all scenarios, the function should select the appropriate variable names, and use type_concept_id fields when available. 

I think currently this is implemented consistently for all scenarios

**Comment by pbr6cornell** [comment]
getDbCohortData does not currently support fetching exposures from
drug_exposure,  only from drug_era and cohort.  The reason is using
drug_exposure would require developing a standardized approach to inferring
end dates and collapsing records.

On Thu, Jan 22, 2015 at 10:09 PM, Martijn Schuemie <notifications@github.com

**Comment by schuemie** [comment]
Agreed. But we were missing support for condition_era. Have added it now. Will push after testing.
