### ISSUE TITLE
Comparing Cohorts with CohortMethod

### ISSUE THREAD

**Issue by jduke99** [OHDSI/CohortMethod#42]
I am curious your thoughts on the virtues of using the cohortMethod as a general comparator tool for cohorts. I have a project where I am not comparing outcome differences between groups but rather want to see how the groups differ. 

It strikes me that CM does this already in its intermediate steps.  Any caveats I should consider?

Patrick and I have chatted about a comparison view for Heracles, but in this case I am looking more for s rank ordered list of concepts.

**Comment by schuemie** [comment]
Well, one limitation is that the comparison between cohorts is based on baseline characteristics (maybe not a limitation, but might not be what you want to achieve). Other than that: yes, I think CM can certainly be useful for comparing cohorts by creating a single summary statistic (the propensity score) to indicate how comparable cohorts are at baseline, and plotting the propensity score distribution.

The ranked list of covariates in the final propensity model (ranked by beta coefficient) can help understand what makes two cohorts different. But we have found that some people have some trouble interpreting the results because the process is quite complicated.
