### ISSUE TITLE
Adding interaction terms to the package made by ATLAS

### ISSUE THREAD

**Issue by chandryou** [OHDSI/CohortMethod#73]
Hello,

I want to add interaction term (old age>=65 yrs) to the package, which is made by ATLAS. 
It seems not difficult to add interaction term to the CohortMethod analysis only. But it is tricky to add interaction term analysis to the package made by ATLAS.
I'm comparing LEGEND package and struggle to figure out how to do this, but it isn't easy..

Is there any easy way to add user-defined interaction term analysis to the ATLAS-made package?

**Comment by chandryou** [comment]
I found that there is an option to add interaction term in ATLAS (and cmAnalysisList.json). Then it would be  easy to add interaction term as a concept_id. 
![image](https://user-images.githubusercontent.com/18287430/48047308-0a32f800-e1db-11e8-9768-8f6c83217012.png)

So now, my question is that how I can add feature, I defined to this package.

**Comment by schuemie** [comment]
Hi Chan,

The ATLAS interface was designed to cover the 80% of studies that do not require fancy stuff.

Defining custom covariates is considered fancy, so to do that you'll still need to write R code. A perhaps overly-complicated example of creating subgroups covariates is in the LEGEND package, with R code [here](https://github.com/OHDSI/Legend/blob/master/R/SubgroupCovariateBuilder.R) which uses the SQL code [here](https://github.com/OHDSI/Legend/blob/master/inst/sql/sql_server/CreateSubgroups.sql).

**Comment by chandryou** [comment]
Thank you for @schuemie 
I found these code.. Still, I couldn't figure out where I should insert this code to be executed among the whole process of the package. 

The whole process of LEGEND is somewhat different from other ATLAS-generated package.. In LEGEND, the custom covariate builder can extract the user-defined feature in 'fetchAllDataFromServer' through 'CustomCmDataObjectBuilding.R'. 
Is this only way to do this fancy stuff? Or can you recommend any other easier way..?

**Comment by gowthamrao** [comment]
@schuemie @chandryou

When CC is fully implemented, as described here

https://github.com/OHDSI/WebAPI/issues/495#issuecomment-433030689

Do you think that would help with the interaction variables and complex/fancy custom covariates?

**Comment by schuemie** [comment]
@chandryou : Yes, the LEGEND code is different in many places to allow execution at a much larger scale. Even though the code I referenced might be a good example of how to define subgroup covariates, a better example of how to include custom covariates in CohortMethod is [this study package](https://github.com/OHDSI/StudyProtocols/tree/master/AhasHfBkleAmputation). [Here](https://github.com/OHDSI/StudyProtocols/blob/master/AhasHfBkleAmputation/R/PriorOutcomeCovariateBuilder.R) is where the custom covariate builder is defined, and [here](https://github.com/OHDSI/StudyProtocols/blob/master/AhasHfBkleAmputation/R/CreateStudyAnalysisDetails.R#L62) you can see how it is inserted in the regular CohortMethod workflow, making it available in the analyses for example for characterization (which is why is was used in this package), or as interaction terms (as done in LEGEND).

@gowthamrao : Yes, I expect that the developments in CC may one day lead to a same situation for covariates that we now have for cohorts: the ability to design them in a user-friendly interface in ATLAS, and then inserting them in a study package for use in the analysis.

**Comment by chandryou** [comment]
Thank you @schuemie  It's really helpful!
I'm closing this thread.
