### ISSUE TITLE
Should the covariates for interaction term be excluded 

### ISSUE THREAD

**Issue by chandryou** [OHDSI/CohortMethod#75]
In the LEGEND, package, the covariates for interaction term be excluded  while creating PS argument. Is there a reason why the covariates for interaction term should be excluded?

**Comment by schuemie** [comment]
As far as I can see that is not necessary. The main reason I took them out in LEGEND is because the interaction variables were added on top of the FeatureExtraction variables, and might 100% overlap for some, so the colinearity might slow the propensity model regression down a bit.

In theory, if the interaction term is a very strong predictor in the propensity model, you may end up under-powered to detect the interactions (after for example PS stratification). But that would mean the problem is intractable anyway (in that particular data set).

**Comment by chandryou** [comment]
As long as I understand, if the interaction term is a very strong predictor in propensity model, and it turns out to be non-significant after matching, then the variable should be included in the PS matching because positive interaction term analysis may be resulted from the biased data set. 

Thank you for the answer @schuemie It's really helpful. :)
